default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DB_NAME") { 'purple_freak' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'purple_freak' } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'purple_freak' } %>_test

production:
  <<: *default
