default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DB_NAME") { 'teste' } %>_<%= Rails.env %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USER") { 'teste' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'teste' } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  username: teste
  password: <%= ENV['TESTE_DATABASE_PASSWORD'] %>
